// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model/book_source.dart';
import 'model/rule/rule_book_info.dart';
import 'model/rule/rule_content.dart';
import 'model/rule/rule_explore.dart';
import 'model/rule/rule_review.dart';
import 'model/rule/rule_search.dart';
import 'model/rule/rule_toc.dart';
import 'model/rule/rule_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 从URL解析书源
Future<List<BookSource>> parseBookSourceFromUrl({required String url}) =>
    RustLib.instance.api
        .crateApiParseBookSourceApiParseBookSourceFromUrl(url: url);
