// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rule_type.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `hash`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `set_rule_types`

/// 正文页规则结构定义
class RuleContent {
  final String? content;
  final String? replaceRegex;
  final String? title;
  final String? nextContentUrl;
  final String? webJs;
  final String? sourceRegex;
  final String? imageStyle;
  final String? payAction;
  final Map<RuleContentField, RuleType> ruleTypes;

  const RuleContent({
    this.content,
    this.replaceRegex,
    this.title,
    this.nextContentUrl,
    this.webJs,
    this.sourceRegex,
    this.imageStyle,
    this.payAction,
    required this.ruleTypes,
  });

  static Future<RuleContent> default_() =>
      RustLib.instance.api.crateApiModelRuleRuleContentRuleContentDefault();

  @override
  int get hashCode =>
      content.hashCode ^
      replaceRegex.hashCode ^
      title.hashCode ^
      nextContentUrl.hashCode ^
      webJs.hashCode ^
      sourceRegex.hashCode ^
      imageStyle.hashCode ^
      payAction.hashCode ^
      ruleTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleContent &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          replaceRegex == other.replaceRegex &&
          title == other.title &&
          nextContentUrl == other.nextContentUrl &&
          webJs == other.webJs &&
          sourceRegex == other.sourceRegex &&
          imageStyle == other.imageStyle &&
          payAction == other.payAction &&
          ruleTypes == other.ruleTypes;
}

enum RuleContentField {
  content,
  replaceRegex,
  title,
  nextContentUrl,
  webJs,
  sourceRegex,
  imageStyle,
  payAction,
  ;
}
