// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rule_type.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `default`, `eq`, `fmt`, `fmt`, `hash`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `set_rule_types`

/// 段评规则结构定义
class RuleReview {
  /// 段评URL
  final String? reviewUrl;

  /// 段评发布者头像规则
  final String? avatarRule;

  /// 段评内容规则
  final String? contentRule;

  /// 段评发布时间规则
  final String? postTimeRule;

  /// 获取段评回复URL
  final String? reviewQuoteUrl;

  /// 点赞URL
  final String? voteUpUrl;

  /// 点踩URL
  final String? voteDownUrl;

  /// 发送回复URL
  final String? postReviewUrl;

  /// 发送回复段评URL
  final String? postQuoteUrl;

  /// 删除段评URL
  final String? deleteUrl;
  final Map<RuleReviewField, RuleType> ruleTypes;

  const RuleReview({
    this.reviewUrl,
    this.avatarRule,
    this.contentRule,
    this.postTimeRule,
    this.reviewQuoteUrl,
    this.voteUpUrl,
    this.voteDownUrl,
    this.postReviewUrl,
    this.postQuoteUrl,
    this.deleteUrl,
    required this.ruleTypes,
  });

  @override
  int get hashCode =>
      reviewUrl.hashCode ^
      avatarRule.hashCode ^
      contentRule.hashCode ^
      postTimeRule.hashCode ^
      reviewQuoteUrl.hashCode ^
      voteUpUrl.hashCode ^
      voteDownUrl.hashCode ^
      postReviewUrl.hashCode ^
      postQuoteUrl.hashCode ^
      deleteUrl.hashCode ^
      ruleTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleReview &&
          runtimeType == other.runtimeType &&
          reviewUrl == other.reviewUrl &&
          avatarRule == other.avatarRule &&
          contentRule == other.contentRule &&
          postTimeRule == other.postTimeRule &&
          reviewQuoteUrl == other.reviewQuoteUrl &&
          voteUpUrl == other.voteUpUrl &&
          voteDownUrl == other.voteDownUrl &&
          postReviewUrl == other.postReviewUrl &&
          postQuoteUrl == other.postQuoteUrl &&
          deleteUrl == other.deleteUrl &&
          ruleTypes == other.ruleTypes;
}

enum RuleReviewField {
  reviewUrl,
  avatarRule,
  contentRule,
  postTimeRule,
  reviewQuoteUrl,
  voteUpUrl,
  voteDownUrl,
  postReviewUrl,
  postQuoteUrl,
  deleteUrl,
  ;
}
