// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.40.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rule_book_info.dart';
import 'rule_content.dart';
import 'rule_explore.dart';
import 'rule_search.dart';
import 'rule_toc.dart';
import 'rule_view.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `set_rule_type`

/// 书源结构定义
class BookSource {
  /// 书源备注
  final String? bookSourceComment;

  /// 书源分组
  final String? bookSourceGroup;

  /// 书源名称
  final String? bookSourceName;

  /// 书源类型，0 文本，1 音频, 2 图片, 3 文件（指的是类似知轩藏书只提供下载的网站）
  final PlatformInt64? bookSourceType;

  /// 书源地址，包括 http/https
  final String? bookSourceUrl;
  final String? bookUrlPattern;
  final String? header;
  final String? loginUrl;

  /// 手动排序编号
  final PlatformInt64? customOrder;

  /// 是否启用
  final bool? enabled;

  /// 每次请求的cookie
  final bool? enabledCookieJar;

  /// 启用发现
  final bool? enabledExplore;

  /// 发现url
  final String? exploreUrl;

  /// 最后更新时间，用于排序
  final PlatformInt64? lastUpdateTime;

  /// 响应时间，用于排序
  final PlatformInt64? respondTime;

  /// 书籍信息页规则
  final RuleBookInfo? ruleBookInfo;

  /// 正文页规则
  final RuleContent? ruleContent;

  /// 发现规则
  final RuleExplore? ruleExplore;

  /// 段评规则
  final RuleReview? ruleReview;

  /// 搜索规则
  final RuleSearch? ruleSearch;

  /// 目录页规则
  final RuleToc? ruleToc;

  /// 搜索url
  final String? searchUrl;

  /// 智能排序的权重
  final PlatformInt64? weight;

  const BookSource({
    this.bookSourceComment,
    this.bookSourceGroup,
    this.bookSourceName,
    this.bookSourceType,
    this.bookSourceUrl,
    this.bookUrlPattern,
    this.header,
    this.loginUrl,
    this.customOrder,
    this.enabled,
    this.enabledCookieJar,
    this.enabledExplore,
    this.exploreUrl,
    this.lastUpdateTime,
    this.respondTime,
    this.ruleBookInfo,
    this.ruleContent,
    this.ruleExplore,
    this.ruleReview,
    this.ruleSearch,
    this.ruleToc,
    this.searchUrl,
    this.weight,
  });

  @override
  int get hashCode =>
      bookSourceComment.hashCode ^
      bookSourceGroup.hashCode ^
      bookSourceName.hashCode ^
      bookSourceType.hashCode ^
      bookSourceUrl.hashCode ^
      bookUrlPattern.hashCode ^
      header.hashCode ^
      loginUrl.hashCode ^
      customOrder.hashCode ^
      enabled.hashCode ^
      enabledCookieJar.hashCode ^
      enabledExplore.hashCode ^
      exploreUrl.hashCode ^
      lastUpdateTime.hashCode ^
      respondTime.hashCode ^
      ruleBookInfo.hashCode ^
      ruleContent.hashCode ^
      ruleExplore.hashCode ^
      ruleReview.hashCode ^
      ruleSearch.hashCode ^
      ruleToc.hashCode ^
      searchUrl.hashCode ^
      weight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSource &&
          runtimeType == other.runtimeType &&
          bookSourceComment == other.bookSourceComment &&
          bookSourceGroup == other.bookSourceGroup &&
          bookSourceName == other.bookSourceName &&
          bookSourceType == other.bookSourceType &&
          bookSourceUrl == other.bookSourceUrl &&
          bookUrlPattern == other.bookUrlPattern &&
          header == other.header &&
          loginUrl == other.loginUrl &&
          customOrder == other.customOrder &&
          enabled == other.enabled &&
          enabledCookieJar == other.enabledCookieJar &&
          enabledExplore == other.enabledExplore &&
          exploreUrl == other.exploreUrl &&
          lastUpdateTime == other.lastUpdateTime &&
          respondTime == other.respondTime &&
          ruleBookInfo == other.ruleBookInfo &&
          ruleContent == other.ruleContent &&
          ruleExplore == other.ruleExplore &&
          ruleReview == other.ruleReview &&
          ruleSearch == other.ruleSearch &&
          ruleToc == other.ruleToc &&
          searchUrl == other.searchUrl &&
          weight == other.weight;
}
