// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.40.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 发现规则结构定义
class RuleExplore {
  final String? author;
  final String? bookList;
  final String? bookUrl;
  final String? coverUrl;
  final String? lastChapter;
  final String? intro;
  final String? name;
  final String? wordCount;
  final String? kind;

  const RuleExplore({
    this.author,
    this.bookList,
    this.bookUrl,
    this.coverUrl,
    this.lastChapter,
    this.intro,
    this.name,
    this.wordCount,
    this.kind,
  });

  @override
  int get hashCode =>
      author.hashCode ^
      bookList.hashCode ^
      bookUrl.hashCode ^
      coverUrl.hashCode ^
      lastChapter.hashCode ^
      intro.hashCode ^
      name.hashCode ^
      wordCount.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleExplore &&
          runtimeType == other.runtimeType &&
          author == other.author &&
          bookList == other.bookList &&
          bookUrl == other.bookUrl &&
          coverUrl == other.coverUrl &&
          lastChapter == other.lastChapter &&
          intro == other.intro &&
          name == other.name &&
          wordCount == other.wordCount &&
          kind == other.kind;
}
