// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rule_type.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `set_rule_type`

/// 目录页规则结构定义
class RuleToc {
  final String? chapterList;
  final String? chapterName;
  final String? chapterUrl;
  final String? isVolume;
  final String? preUpdateJson;
  final String? formatJs;
  final String? isVip;
  final String? isPay;
  final String? nextTocUrl;
  final String? updateTime;
  final RuleType? ruleType;

  const RuleToc({
    this.chapterList,
    this.chapterName,
    this.chapterUrl,
    this.isVolume,
    this.preUpdateJson,
    this.formatJs,
    this.isVip,
    this.isPay,
    this.nextTocUrl,
    this.updateTime,
    this.ruleType,
  });

  @override
  int get hashCode =>
      chapterList.hashCode ^
      chapterName.hashCode ^
      chapterUrl.hashCode ^
      isVolume.hashCode ^
      preUpdateJson.hashCode ^
      formatJs.hashCode ^
      isVip.hashCode ^
      isPay.hashCode ^
      nextTocUrl.hashCode ^
      updateTime.hashCode ^
      ruleType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleToc &&
          runtimeType == other.runtimeType &&
          chapterList == other.chapterList &&
          chapterName == other.chapterName &&
          chapterUrl == other.chapterUrl &&
          isVolume == other.isVolume &&
          preUpdateJson == other.preUpdateJson &&
          formatJs == other.formatJs &&
          isVip == other.isVip &&
          isPay == other.isPay &&
          nextTocUrl == other.nextTocUrl &&
          updateTime == other.updateTime &&
          ruleType == other.ruleType;
}
