// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.40.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 正文页规则结构定义
class RuleContent {
  final String? content;
  final String? replaceRegex;
  final String? title;
  final String? nextContentUrl;
  final String? webJs;
  final String? sourceRegex;
  final String? imageStyle;
  final String? payAction;

  const RuleContent({
    this.content,
    this.replaceRegex,
    this.title,
    this.nextContentUrl,
    this.webJs,
    this.sourceRegex,
    this.imageStyle,
    this.payAction,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      replaceRegex.hashCode ^
      title.hashCode ^
      nextContentUrl.hashCode ^
      webJs.hashCode ^
      sourceRegex.hashCode ^
      imageStyle.hashCode ^
      payAction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleContent &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          replaceRegex == other.replaceRegex &&
          title == other.title &&
          nextContentUrl == other.nextContentUrl &&
          webJs == other.webJs &&
          sourceRegex == other.sourceRegex &&
          imageStyle == other.imageStyle &&
          payAction == other.payAction;
}
