// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 搜索规则结构定义
class SearchBook {
  final String? author;
  final String? bookUrl;
  final String? coverUrl;
  final String? intro;
  final String? name;
  final String? wordCount;
  final String? kind;

  const SearchBook({
    this.author,
    this.bookUrl,
    this.coverUrl,
    this.intro,
    this.name,
    this.wordCount,
    this.kind,
  });

  static Future<SearchBook> default_() =>
      RustLib.instance.api.crateApiModelSearchBookSearchBookDefault();

  @override
  int get hashCode =>
      author.hashCode ^
      bookUrl.hashCode ^
      coverUrl.hashCode ^
      intro.hashCode ^
      name.hashCode ^
      wordCount.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchBook &&
          runtimeType == other.runtimeType &&
          author == other.author &&
          bookUrl == other.bookUrl &&
          coverUrl == other.coverUrl &&
          intro == other.intro &&
          name == other.name &&
          wordCount == other.wordCount &&
          kind == other.kind;
}
