// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/model/book_source.dart';
import 'api/model/rule_book_info.dart';
import 'api/model/rule_content.dart';
import 'api/model/rule_explore.dart';
import 'api/model/rule_search.dart';
import 'api/model/rule_toc.dart';
import 'api/model/rule_type.dart';
import 'api/model/rule_view.dart';
import 'api/parse_book_source_api.dart';
import 'api/search_book_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, RuleType> dco_decode_Map_String_rule_type(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookSource dco_decode_book_source(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BookSource dco_decode_box_autoadd_book_source(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RuleBookInfo dco_decode_box_autoadd_rule_book_info(dynamic raw);

  @protected
  RuleContent dco_decode_box_autoadd_rule_content(dynamic raw);

  @protected
  RuleExplore dco_decode_box_autoadd_rule_explore(dynamic raw);

  @protected
  RuleReview dco_decode_box_autoadd_rule_review(dynamic raw);

  @protected
  RuleSearch dco_decode_box_autoadd_rule_search(dynamic raw);

  @protected
  RuleToc dco_decode_box_autoadd_rule_toc(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<BookSource> dco_decode_list_book_source(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, RuleType)> dco_decode_list_record_string_rule_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RuleBookInfo? dco_decode_opt_box_autoadd_rule_book_info(dynamic raw);

  @protected
  RuleContent? dco_decode_opt_box_autoadd_rule_content(dynamic raw);

  @protected
  RuleExplore? dco_decode_opt_box_autoadd_rule_explore(dynamic raw);

  @protected
  RuleReview? dco_decode_opt_box_autoadd_rule_review(dynamic raw);

  @protected
  RuleSearch? dco_decode_opt_box_autoadd_rule_search(dynamic raw);

  @protected
  RuleToc? dco_decode_opt_box_autoadd_rule_toc(dynamic raw);

  @protected
  (String, RuleType) dco_decode_record_string_rule_type(dynamic raw);

  @protected
  RuleBookInfo dco_decode_rule_book_info(dynamic raw);

  @protected
  RuleContent dco_decode_rule_content(dynamic raw);

  @protected
  RuleExplore dco_decode_rule_explore(dynamic raw);

  @protected
  RuleReview dco_decode_rule_review(dynamic raw);

  @protected
  RuleSearch dco_decode_rule_search(dynamic raw);

  @protected
  RuleToc dco_decode_rule_toc(dynamic raw);

  @protected
  RuleType dco_decode_rule_type(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, RuleType> sse_decode_Map_String_rule_type(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookSource sse_decode_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BookSource sse_decode_box_autoadd_book_source(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RuleBookInfo sse_decode_box_autoadd_rule_book_info(
      SseDeserializer deserializer);

  @protected
  RuleContent sse_decode_box_autoadd_rule_content(SseDeserializer deserializer);

  @protected
  RuleExplore sse_decode_box_autoadd_rule_explore(SseDeserializer deserializer);

  @protected
  RuleReview sse_decode_box_autoadd_rule_review(SseDeserializer deserializer);

  @protected
  RuleSearch sse_decode_box_autoadd_rule_search(SseDeserializer deserializer);

  @protected
  RuleToc sse_decode_box_autoadd_rule_toc(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<BookSource> sse_decode_list_book_source(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, RuleType)> sse_decode_list_record_string_rule_type(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RuleBookInfo? sse_decode_opt_box_autoadd_rule_book_info(
      SseDeserializer deserializer);

  @protected
  RuleContent? sse_decode_opt_box_autoadd_rule_content(
      SseDeserializer deserializer);

  @protected
  RuleExplore? sse_decode_opt_box_autoadd_rule_explore(
      SseDeserializer deserializer);

  @protected
  RuleReview? sse_decode_opt_box_autoadd_rule_review(
      SseDeserializer deserializer);

  @protected
  RuleSearch? sse_decode_opt_box_autoadd_rule_search(
      SseDeserializer deserializer);

  @protected
  RuleToc? sse_decode_opt_box_autoadd_rule_toc(SseDeserializer deserializer);

  @protected
  (String, RuleType) sse_decode_record_string_rule_type(
      SseDeserializer deserializer);

  @protected
  RuleBookInfo sse_decode_rule_book_info(SseDeserializer deserializer);

  @protected
  RuleContent sse_decode_rule_content(SseDeserializer deserializer);

  @protected
  RuleExplore sse_decode_rule_explore(SseDeserializer deserializer);

  @protected
  RuleReview sse_decode_rule_review(SseDeserializer deserializer);

  @protected
  RuleSearch sse_decode_rule_search(SseDeserializer deserializer);

  @protected
  RuleToc sse_decode_rule_toc(SseDeserializer deserializer);

  @protected
  RuleType sse_decode_rule_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_rule_type(
      Map<String, RuleType> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_book_source(BookSource self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_source(
      BookSource self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_book_info(
      RuleBookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_content(
      RuleContent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_explore(
      RuleExplore self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_review(
      RuleReview self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_search(
      RuleSearch self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rule_toc(RuleToc self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_book_source(
      List<BookSource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_rule_type(
      List<(String, RuleType)> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_book_info(
      RuleBookInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_content(
      RuleContent? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_explore(
      RuleExplore? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_review(
      RuleReview? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_search(
      RuleSearch? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rule_toc(
      RuleToc? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_rule_type(
      (String, RuleType) self, SseSerializer serializer);

  @protected
  void sse_encode_rule_book_info(RuleBookInfo self, SseSerializer serializer);

  @protected
  void sse_encode_rule_content(RuleContent self, SseSerializer serializer);

  @protected
  void sse_encode_rule_explore(RuleExplore self, SseSerializer serializer);

  @protected
  void sse_encode_rule_review(RuleReview self, SseSerializer serializer);

  @protected
  void sse_encode_rule_search(RuleSearch self, SseSerializer serializer);

  @protected
  void sse_encode_rule_toc(RuleToc self, SseSerializer serializer);

  @protected
  void sse_encode_rule_type(RuleType self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
