on: [push, pull_request]

name: Continuous integration

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
        working-directory: ./rust
      - run: cargo clippy
        working-directory: ./rust
